spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=auth_user
spring.datasource.password=auth_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
springdoc.swagger-ui.path=/swagger-ui
server.port=8081

# Service URLs for inter-service communication
services.profile.url=http://localhost:8083
services.tenant.url=http://localhost:8082
