spring.application.name=mindmap-service
spring.datasource.url=jdbc:postgresql://localhost:5433/brain_mindmap
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
springdoc.swagger-ui.path=/swagger-ui
server.port=8087
