spring.application.name=mindmap-service
spring.datasource.url=jdbc:postgresql://localhost:5432/mindmap
spring.datasource.username=mindmap_user
spring.datasource.password=mindmap_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
springdoc.swagger-ui.path=/swagger-ui
server.port=8087
