spring.application.name=tenant-service
spring.datasource.url=jdbc:postgresql://localhost:5432/tenant
spring.datasource.username=tenant_user
spring.datasource.password=tenant_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
server.port=8082